default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: bloccit
  username: bloccit
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bloccit_test
  username: bloccit
  pool: 5
  timeout: 5000
#
#production:
#  adapter: postgresql
#  database: my_database_production
#  pool: 5
#  timeout: 5000
